{
 "title": "BasketAPI",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "traceId", "label": "Trace ID" }
  ]
 },
 "panels": [
  { "title": "Ordering.API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average Request time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "service": "basket-api" }
   ]
  },
  {
   "title": "Number of requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    { "operation": "CreateOrder", "service": "ordering-api" }
   ]
  },
  {
   "title": "Service Availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "operation": "GET /health", "service": "ordering-api" }
   ]
  },
  {
   "title": "Create Order Requests",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "operation": "CreateOrder", "query": "${traceId}", "service": "ordering-api" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "traces",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "query": "${traceId}" }
   ]
  },
  { "title": "Basket.API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Requests over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    { "service": "basket-api" }
   ]
  },
  {
   "title": "Number of /GET",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "get_basket_requests_total{exported_job=\"basket-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Request time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "service": "basket-api" }
   ]
  },
  {
   "title": "Number of requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    { "service": "basket-api" }
   ]
  },
  {
   "title": "Service Availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "traces",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 29 },
   "targets": [
    { "query": "${traceId}" }
   ]
  },
  {
   "title": "Requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    { "query": "${traceId}", "service": "basket-api" }
   ]
  }
 ]
}