receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4316
      http:
        endpoint: 0.0.0.0:4315

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
